[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
ethereumSepolia = "${SEPOLIA_RPC_URL}"
avalancheFuji = "${FUJI_RPC_URL}"
dispatchTestnet = "${DISPATCH_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
